application: vensplit
version: 1
runtime: go
api_version: go1

handlers:
- url: /
  upload: templates/index.html
  static_files: templates/index.html
- url: /config
  login: admin
  upload: templates/config.html
  static_files: templates/config.html
- url: /.*
  script: _go_app
